services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Bzga\BzgaBeratungsstellensucheFamilienplanung\:
    resource: '../Classes/*'

  Bzga\BzgaBeratungsstellensucheFamilienplanung\EventListener\EntryFormEventListener:
    tags:
      - name: event.listener
        identifier: 'enhance-view-with-religion'

  Bzga\BzgaBeratungsstellensucheFamilienplanung\EventListener\EntryNameConverterEventListener:
    tags:
      - name: event.listener
        identifier: 'enhance-name-mapping-converter'

  Bzga\BzgaBeratungsstellensucheFamilienplanung\EventListener\EntryNormalizerEventListener:
    tags:
      - name: event.listener
        identifier: 'enhance-normalizer-for-new-properties'

  Bzga\BzgaBeratungsstellensucheFamilienplanung\EventListener\TruncateAllEventListener:
    tags:
      - name: event.listener
        identifier: 'truncate-all-dependencies-for-entry-import'
